// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZIisxWx7evfHcAA3RLDXkpKTAjCA7O7A',
    appId: '1:529973096850:web:6518337e63c4c7119d514b',
    messagingSenderId: '529973096850',
    projectId: 'bloquera-demo-portfolio',
    authDomain: 'bloquera-demo-portfolio.firebaseapp.com',
    storageBucket: 'bloquera-demo-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTQrxV7wfm_3uzlaB3HJdW2_3ChHN-ah0',
    appId: '1:529973096850:android:71bc9eb15549c3ca9d514b',
    messagingSenderId: '529973096850',
    projectId: 'bloquera-demo-portfolio',
    storageBucket: 'bloquera-demo-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzgez0RSg_0Srmb4bjL2cik0uPEH2J-Zo',
    appId: '1:529973096850:ios:60f32a5d64b82bb19d514b',
    messagingSenderId: '529973096850',
    projectId: 'bloquera-demo-portfolio',
    storageBucket: 'bloquera-demo-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.dashBloquera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzgez0RSg_0Srmb4bjL2cik0uPEH2J-Zo',
    appId: '1:529973096850:ios:60f32a5d64b82bb19d514b',
    messagingSenderId: '529973096850',
    projectId: 'bloquera-demo-portfolio',
    storageBucket: 'bloquera-demo-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.dashBloquera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZIisxWx7evfHcAA3RLDXkpKTAjCA7O7A',
    appId: '1:529973096850:web:48008180da2f1cd89d514b',
    messagingSenderId: '529973096850',
    projectId: 'bloquera-demo-portfolio',
    authDomain: 'bloquera-demo-portfolio.firebaseapp.com',
    storageBucket: 'bloquera-demo-portfolio.firebasestorage.app',
  );
}
